### ISSUE TITLE
Favorites Bug When Adding Multiple Movies

### ISSUE THREAD

**Issue by HOB3R** [r-meissner/tmdb-api-with-parcel#3]
#### Description
When adding multiple movies to the favorites in our Movie Diary application, only the last selected movie appears in the favorites.

#### Steps to Reproduce
1. Open the application.
2. Add several movies to the favorites, one by one, directly from the main page.
3. Go to the favorites page.

#### Expected Behavior
All selected movies should be displayed in the favorites.

#### Actual Behavior
Only the last added movie is displayed in the favorites.

#### Additional Information
I have tested this in multiple browsers, but it may be possible that the issue only occurs on my setup.

**Comment by r-meissner** [comment]
The error occured because the previously stored favorites were only checked once and not updated before adding a new one. So on loading, the previous list of favorites was stored in the previousStorage variable. When you clicked on the favorite button of one movie, it replaced the localStorage with the previosuStorage variable plus the movie. However, every instance of the button used the same previousStorage variable, so the list was always replaced with the first instance of the list plus that particular movie.

I fixed it by adding a step to update the previousStorage variable to the event listener.
